name: Publish Java

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - run: |
          make clean
      - run: |
          make compile
      - run: |
          VERSION=${GITHUB_REF#refs/*/} PASSPHRASE=${{ secrets.OSSRH_PASSWORD }} make release
        env:
          OSSRH_USERNAME: 'smartystreets'
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}