name: Publish Java

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: $OSSRH_USERNAME
          server-password: $OSSRH_PASSWORD
      - run: |
          make clean
      - run: |
          make compile
      - run: |
          VERSION=${GITHUB_REF#refs/*/} PASSPHRASE=${{ secrets.GPG_PASSPHRASE }} make release
        env:
            GPG_SIGNING_KEY: ${{ secrets.GPG_PASSPHRASE }}
            OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
            OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}