name: Publish Java

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      - run: |
          make clean
          make compile
          VERSION=${GITHUB_REF#refs/*/} make release
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}