name: Publish Java

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: $OSSRH_USERNAME
          server-password: $OSSRH_PASSWORD

      - run: |
          mkdir -p ~/.m2
          echo "<settingsSecurity><master>$(mvn --encrypt-master-password "${OSSRH_PASSWORD}")</master></settingsSecurity>" > ~/.m2/settings-security.xml
          echo -e "$OSSRH_GPG_SECRET_KEY" | gpg --batch --import
          VERSION="${GITHUB_REF#refs/*/}" make publish
        env:
            OSSRH_GPG_SECRET_KEY:            ${{ secrets.OSSRH_GPG_SECRET_KEY }}
            OSSRH_GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}
            OSSRH_USERNAME:                  ${{ secrets.OSSRH_USERNAME }}
            OSSRH_PASSWORD:                  ${{ secrets.OSSRH_PASSWORD }}
